name: edm_solutions
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version info
version: 1.0.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  get: ^4.7.2
  get_storage: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  dio: ^4.0.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  signature: ^5.4.0
  url_launcher: ^6.2.5
  credit_card_validator: ^2.1.0
  flutter_stripe: ^10.1.0
  pdf: ^3.10.1
  printing: ^5.10.7
  path_provider: ^2.0.15

  # API & Network
  http: ^1.2.0

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Image Picker for document upload
  image_picker: ^1.0.7
  

  # Date formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/edm_solutions.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
